---
name: epp_adrija
channels:
  - conda-forge
  - nodefaults
dependencies:
  - conda-lock
  - ipykernel
  - jupyterlab
  - linearmodels
  - pandas
  - pdbpp
  - pip >=21.1
  - plotly>=5.13.0
  - plotnine
  - pre-commit
  - pytask-latex
  - pytask-parallel
  - pytask>=0.2
  - pytest
  - pytest-cov
  - pytest-xdist
  - python-graphviz
  - python=3.11
  - pyyaml
  - numpy
  - scikit-learn
  - setuptools_scm
  - statsmodels
  - toml
  - pip:
      - -e .
      - kaleido
